name: riverpod_gpt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.5
  freezed_annotation: ^2.2.0
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  source_gen: ^1.2.7
  flutter_gen_runner: ^5.3.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/icon/'
    - 'assets/images/'

flutter_gen:
  output: lib/src/_generated/gen/
  lineLength: 80

  integrations:
    flutter_svg: true
